export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SEARCH_LOCATIONS_REQUEST = "SEARCH_LOCATIONS_REQUEST";
export const SEARCH_LOCATIONS_SUCCESS = "SEARCH_LOCATIONS_SUCCESS";
export const SEARCH_LOCATIONS_FAIL = "SEARCH_LOCATIONS_FAIL";